import { JacketPart } from "./types";

export const PARTS: JacketPart[] = [
  {
    k: 'h2s',
    nm: 'H₂S Sensor',
    fn: 'Toxic hydrogen sulphide detection',
    loc: 'Upper chest / breathing zone',
    bus: 'ADC GPIO 35 · heater on GPIO 12',
    ic: 'gas',
    p: [-0.24, 1.74, 0.28],
    face: 'front',
    side: 'left',
  },
  {
    k: 'rad',
    nm: 'SBM-20 GM Tube',
    fn: 'Radiation detection',
    loc: 'Outer jacket (rib / chest)',
    bus: 'High-voltage 400V bias · Pulse counter GPIO 14',
    ic: 'rad',
    p: [0.26, 1.42, 0.26],
    face: 'front',
    side: 'right',
  },
  {
    k: 'dht',
    nm: 'DHT22',
    fn: 'Temperature & humidity sensor',
    loc: 'Upper chest (right lapel)',
    bus: 'GPIO 4 · Single-bus digital',
    ic: 'therm',
    p: [0.24, 1.68, 0.28],
    face: 'front',
    side: 'right',
  },
  {
    k: 'pms',
    nm: 'PMS5003',
    fn: 'Airborne dust / particulate matter',
    loc: 'Upper chest (left air intake)',
    bus: 'UART2 · RX 16 / TX 17 (laser scattering)',
    ic: 'dust',
    p: [-0.30, 1.48, 0.26],
    face: 'front',
    side: 'left',
  },
  {
    k: 'max',
    nm: 'MAX30102',
    fn: 'Heart rate & SpO₂ sensor',
    loc: 'Wrist / inner cuff (skin contact)',
    bus: 'I²C 0x57 · SDA 21 / SCL 22',
    ic: 'heart',
    p: [0.52, 1.01, 0.12],
    face: 'front',
    side: 'right',
  },
  {
    k: 'sos',
    nm: 'SOS Button',
    fn: 'Emergency distress button',
    loc: 'Chest / front (prominent tactile badge)',
    bus: 'GPIO 19 · Hardware interrupt debounce',
    ic: 'sos',
    p: [0.00, 1.54, 0.32],
    face: 'front',
    side: 'right',
  },
  {
    k: 'lora',
    nm: 'LoRa Module + Antenna',
    fn: 'Long-range communication (sub-GHz)',
    loc: 'Shoulder / chest with top whip antenna',
    bus: 'SX1276 868MHz · SPI + Whip antenna',
    ic: 'lora',
    p: [-0.34, 1.82, 0.18],
    face: 'front',
    side: 'left',
  },
  {
    k: 'uwb',
    nm: 'UWB Tag',
    fn: 'Underground positioning (GPS substitute)',
    loc: 'Upper back / shoulder (between blades)',
    bus: 'DW1000 SPI · CS 15 · IRQ 27 (±15 cm fix)',
    ic: 'uwb',
    p: [0.00, 1.82, -0.28],
    face: 'back',
    side: 'right',
  },
  {
    k: 'pcm',
    nm: 'PCM Cooling Pack',
    fn: 'Phase-change thermal heat relief',
    loc: 'Inner lower back (lumbar pad)',
    bus: '28°C paraffin PCM quilted matrix pad',
    ic: 'pcm',
    p: [0.00, 1.25, -0.24],
    face: 'inside',
    side: 'left',
  },
  {
    k: 'bat',
    nm: 'Battery Pack',
    fn: 'Safe rechargeable power supply',
    loc: 'Inside pocket (zippered compartment)',
    bus: '3.7V 5000mAh LiPo · protected BMS',
    ic: 'batt',
    p: [-0.17, 1.34, -0.08],
    face: 'inside',
    side: 'left',
  },
  {
    k: 'esp32',
    nm: 'ESP32 MCU Board',
    fn: 'Central controller & edge processor',
    loc: 'Inner chest electronics pocket',
    bus: 'Dual-core 240MHz · BLE/Wi-Fi/Sensors',
    ic: 'pcb',
    p: [0.03, 1.44, 0.30],
    face: 'front',
    side: 'right',
  },
  {
    k: 'vib',
    nm: 'Vibration Motor',
    fn: 'Tactile emergency warning',
    loc: 'Shoulder strap (close to collarbone)',
    bus: 'GPIO 13 · MOSFET driver',
    ic: 'vib',
    p: [-0.22, 1.86, 0.16],
    face: 'front',
    side: 'left',
  },
  {
    k: 'buz',
    nm: 'Audible Buzzer',
    fn: 'Acoustic alarm sounder',
    loc: 'Collar / upper lapel',
    bus: 'GPIO 25 · 2.7 kHz resonant horn',
    ic: 'horn',
    p: [-0.18, 1.94, 0.22],
    face: 'front',
    side: 'left',
  },
  {
    k: 'coat',
    nm: 'Smart Safety Jacket',
    fn: 'Weatherproof high-visibility garment',
    loc: 'Complete outer wearable',
    bus: 'EN ISO 20471 Class 3 · flame retardant',
    ic: 'coat',
    nopin: true,
  }
];
